server:
  port: 8077
spring:
  application:
    name: rabbitmq-provider

  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated

